version: "3.9"

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - product-catalog-service
      - shopping-cart-service
      - order-service
      - payment-service
      - notification-service

  user-service:
    build: ./services/user-service
    ports:
      - "8001:8001"

  product-catalog-service:
    build: ./services/product-catalog-service
    ports:
      - "8002:8002"

  shopping-cart-service:
    build: ./services/shopping-cart-service
    ports:
      - "8003:8003"

  order-service:
    build: ./services/order-service
    ports:
      - "8004:8004"

  payment-service:
    build: ./services/payment-service
    ports:
      - "8005:8005"

  notification-service:
    build: ./services/notification-service
    ports:
      - "8006:8006"
